// jane
export const ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJtYXhfY2Fsb3JpZXNfcGVyX2RheSI6IjIxMDAiLCJyb2xlIjoicmVndWxhcl91c2VyIiwidXNlcm5hbWUiOiJqYW5lIn0.M6vL17FQZ7emw7MYaMVT2PsweNRrrZ_5eVy3tB1wGKM";

// john
// export const ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJtYXhfY2Fsb3JpZXNfcGVyX2RheSI6IjIxMDAiLCJyb2xlIjoicmVndWxhcl91c2VyIiwidXNlcm5hbWUiOiJqb2huIn0.QlhPRbHm3FMdruEE4xE_yAwDlXTOjgQ0U2lGx0DHqI0";

// admin
// export const ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJtYXhfY2Fsb3JpZXNfcGVyX2RheSI6IjIxMDAiLCJyb2xlIjoiYWRtaW4iLCJ1c2VybmFtZSI6ImFkbWluIn0.LbnJNcI1zo95ADCtdAvsqllPsBZ3SA4pAvg69qfJxVM"
